// Copyright (c) 2026 The btcd developers
// Use of this source code is governed by an ISC
// license that can be found in the LICENSE file.

package main

import (
	"crypto/hmac"
	"crypto/sha256"
	"crypto/sha512"
	"embed"
	"encoding/binary"
	"fmt"
	"math/big"
	"strings"
)

//go:embed wordlist_english.txt
var englishWordlistFile embed.FS

// englishWordlist holds the 2048 words of the BIP39 English wordlist, in
// order, so that wordlist[i] is the word represented by the 11-bit value i.
var englishWordlist []string

// englishWordIndex maps each word back to its 11-bit index in
// englishWordlist for fast validation/decoding.
var englishWordIndex map[string]uint16

func init() {
	raw, err := englishWordlistFile.ReadFile("wordlist_english.txt")
	if err != nil {
		panic(fmt.Sprintf("bip39scan: failed to load embedded wordlist: %v",
			err))
	}

	englishWordlist = strings.Fields(string(raw))
	if len(englishWordlist) != 2048 {
		panic(fmt.Sprintf("bip39scan: english wordlist has %d words, "+
			"want 2048", len(englishWordlist)))
	}

	englishWordIndex = make(map[string]uint16, len(englishWordlist))
	for i, word := range englishWordlist {
		englishWordIndex[word] = uint16(i)
	}
}

// entropyBitsByWordCount maps a valid BIP39 mnemonic word count to the
// number of entropy bits (ENT) it encodes, per the table in BIP39.
var entropyBitsByWordCount = map[int]int{
	12: 128,
	15: 160,
	18: 192,
	21: 224,
	24: 256,
}

// ValidateMnemonic checks that mnemonic is a well-formed BIP39 English
// mnemonic: every word must appear in the English wordlist, the word count
// must be one of the standard lengths (12, 15, 18, 21, or 24), and the
// trailing checksum bits must match the SHA-256 hash of the encoded
// entropy.
//
// NOTE: this implementation assumes the mnemonic (and, in SeedFromMnemonic,
// the passphrase) are already provided in NFKD-normalized form, which is
// automatically true for plain ASCII input such as the standard English
// wordlist and typical ASCII passphrases. Non-ASCII passphrases that are not
// already NFKD-normalized may produce a seed that differs from other BIP39
// implementations that normalize internally.
func ValidateMnemonic(mnemonic string) error {
	_, err := entropyFromMnemonic(mnemonic)
	return err
}

// entropyFromMnemonic decodes mnemonic into its underlying entropy after
// validating its word count, wordlist membership, and checksum.
func entropyFromMnemonic(mnemonic string) ([]byte, error) {
	words := strings.Fields(mnemonic)

	numWords := len(words)
	entBits, ok := entropyBitsByWordCount[numWords]
	if !ok {
		return nil, fmt.Errorf("mnemonic has %d words; valid lengths are "+
			"12, 15, 18, 21, or 24", numWords)
	}

	// Reassemble the words into a single (numWords * 11)-bit integer,
	// where csBits = totalBits / 33 and entBits = totalBits - csBits.
	acc := new(big.Int)
	for i, word := range words {
		idx, ok := englishWordIndex[strings.ToLower(word)]
		if !ok {
			return nil, fmt.Errorf("word %d (%q) is not in the BIP39 "+
				"English wordlist", i+1, word)
		}
		acc.Lsh(acc, 11)
		acc.Or(acc, big.NewInt(int64(idx)))
	}

	totalBits := numWords * 11
	csBits := totalBits / 33
	if entBits != totalBits-csBits {
		// Unreachable given entropyBitsByWordCount above, but guards
		// against future edits to the table going out of sync with the
		// BIP39 checksum-length formula.
		return nil, fmt.Errorf("internal error: inconsistent entropy/"+
			"checksum bit split for %d words", numWords)
	}

	mask := new(big.Int).Lsh(big.NewInt(1), uint(csBits))
	mask.Sub(mask, big.NewInt(1))

	checksumBits := new(big.Int).And(acc, mask)
	entropyInt := new(big.Int).Rsh(acc, uint(csBits))

	entropy := make([]byte, entBits/8)
	entropyInt.FillBytes(entropy)

	hash := sha256.Sum256(entropy)
	computedChecksum := new(big.Int).SetBytes(hash[:])
	computedChecksum.Rsh(computedChecksum, uint(256-csBits))

	if computedChecksum.Cmp(checksumBits) != 0 {
		return nil, fmt.Errorf("invalid mnemonic checksum")
	}

	return entropy, nil
}

// SeedFromMnemonic derives the 64-byte BIP39 seed for mnemonic and
// passphrase using PBKDF2-HMAC-SHA512 with 2048 rounds, per BIP39. The
// mnemonic's checksum is validated first; use SeedFromMnemonicUnchecked to
// derive a seed from a mnemonic without checksum validation (e.g. one
// generated by another wallet that used a non-English wordlist).
func SeedFromMnemonic(mnemonic, passphrase string) ([]byte, error) {
	if err := ValidateMnemonic(mnemonic); err != nil {
		return nil, err
	}
	return SeedFromMnemonicUnchecked(mnemonic, passphrase), nil
}

// SeedFromMnemonicUnchecked derives the 64-byte BIP39 seed for mnemonic and
// passphrase without validating the mnemonic's checksum or wordlist
// membership first.
func SeedFromMnemonicUnchecked(mnemonic, passphrase string) []byte {
	normalizedMnemonic := strings.Join(strings.Fields(mnemonic), " ")
	password := []byte(normalizedMnemonic)
	salt := []byte("mnemonic" + passphrase)

	return pbkdf2HMACSHA512(password, salt, 2048, 64)
}

// pbkdf2HMACSHA512 implements PBKDF2 (RFC 8018) using HMAC-SHA512 as its
// pseudorandom function, returning a derived key of keyLen bytes.
func pbkdf2HMACSHA512(password, salt []byte, iterations, keyLen int) []byte {
	prf := hmac.New(sha512.New, password)
	hashLen := prf.Size()

	numBlocks := (keyLen + hashLen - 1) / hashLen

	derivedKey := make([]byte, 0, numBlocks*hashLen)
	blockIndex := make([]byte, 4)

	for block := 1; block <= numBlocks; block++ {
		binary.BigEndian.PutUint32(blockIndex, uint32(block))

		prf.Reset()
		prf.Write(salt)
		prf.Write(blockIndex)
		u := prf.Sum(nil)

		t := make([]byte, len(u))
		copy(t, u)

		for iter := 1; iter < iterations; iter++ {
			prf.Reset()
			prf.Write(u)
			u = prf.Sum(nil)

			for i := range t {
				t[i] ^= u[i]
			}
		}

		derivedKey = append(derivedKey, t...)
	}

	return derivedKey[:keyLen]
}
